/** TechLab - Desarrollador: Pablo De Lillo. */
package com.techlab.app;
import com.techlab.productos.*;
import com.techlab.pedidos.*;
import com.techlab.servicios.*;
import com.techlab.utilidades.Validaciones;
import java.time.LocalDate;
import java.util.*;
public class Main {
 private static final Scanner sc=new Scanner(System.in);
 private static final CategoriaService categorias=new CategoriaService();
 private static final ProductoService productos=new ProductoService();
 private static final PedidoService pedidos=new PedidoService();
 public static void main(String[] args){
  cargarEjemplos();
  try{int op;do{System.out.println("\n===== TECHLAB =====\n1) Productos\n2) Categorías\n3) Pedidos\n0) Salir");op=Validaciones.entero(sc,"Opción: ");switch(op){case 1:menuProductos();break;case 2:menuCategorias();break;case 3:menuPedidos();break;case 0:System.out.println("Hasta luego.");break;default:System.out.println("Opción inválida.");}}while(op!=0);}catch(IllegalStateException e){System.out.println("Entrada finalizada.");}
 }
 private static void menuCategorias(){int op;do{System.out.println("\n--- CATEGORÍAS ---\n1) Crear\n2) Listar\n3) Buscar\n4) Actualizar\n5) Eliminar\n0) Volver");op=Validaciones.entero(sc,"Opción: ");try{switch(op){case 1:Categoria c=categorias.crear(Validaciones.texto(sc,"Nombre: "),Validaciones.texto(sc,"Descripción: "));System.out.println("Creada: "+c);break;case 2:categorias.listar().forEach(System.out::println);break;case 3:System.out.println(categorias.buscar(Validaciones.positivo(sc,"ID: ")));break;case 4:int id=Validaciones.positivo(sc,"ID: ");categorias.actualizar(id,Validaciones.texto(sc,"Nuevo nombre: "),Validaciones.texto(sc,"Nueva descripción: "));System.out.println("Actualizada.");break;case 5:int borrar=Validaciones.positivo(sc,"ID: ");System.out.println(categorias.buscar(borrar));if(Validaciones.confirmar(sc,"¿Eliminar? (S/N): ")){categorias.eliminar(borrar,productos.getProductos());System.out.println("Eliminada.");}break;case 0:break;default:System.out.println("Opción inválida.");}}catch(IllegalArgumentException e){System.out.println("Error: "+e.getMessage());}}while(op!=0);}
 private static void menuProductos(){int op;do{System.out.println("\n--- PRODUCTOS ---\n1) Agregar\n2) Listar\n3) Buscar / actualizar\n4) Eliminar\n0) Volver");op=Validaciones.entero(sc,"Opción: ");try{switch(op){case 1:agregarProducto();break;case 2:productos.listarProductos();break;case 3:actualizarProducto();break;case 4:productos.listarProductos();int id=Validaciones.positivo(sc,"ID a eliminar: ");System.out.println(productos.buscarPorId(id));if(Validaciones.confirmar(sc,"¿Eliminar? (S/N): ")){productos.eliminarPorId(id);System.out.println("Eliminado.");}break;case 0:break;default:System.out.println("Opción inválida.");}}catch(Exception e){System.out.println("Error: "+e.getMessage());}}while(op!=0);}
 private static void agregarProducto(){System.out.println("1) General  2) Bebida  3) Comida");int tipo=Validaciones.entero(sc,"Tipo: ");if(tipo<1||tipo>3){System.out.println("Tipo inválido.");return;}categorias.listar().forEach(System.out::println);Categoria c=categorias.buscar(Validaciones.positivo(sc,"ID categoría: "));String nombre=Validaciones.texto(sc,"Nombre: ");double precio=Validaciones.decimal(sc,"Precio: ",false);int stock=Validaciones.noNegativo(sc,"Stock: ");Producto p=tipo==2?new Bebida(nombre,precio,stock,c,Validaciones.decimal(sc,"Litros: ",true)):tipo==3?new Comida(nombre,precio,stock,c,Validaciones.fecha(sc,"Vencimiento (AAAA-MM-DD): ")):new ProductoGeneral(nombre,precio,stock,c);productos.agregarProducto(p);System.out.println("Agregado: "+p);}
 private static void actualizarProducto()throws Exception{System.out.println("1) Buscar por ID  2) Buscar por nombre");int tipo=Validaciones.entero(sc,"Opción: ");Producto p;if(tipo==1)p=productos.buscarPorId(Validaciones.positivo(sc,"ID: "));else if(tipo==2){List<Producto> lista=productos.buscarPorNombre(Validaciones.texto(sc,"Nombre: "));lista.forEach(System.out::println);p=productos.buscarPorId(Validaciones.positivo(sc,"ID a seleccionar: "));if(!lista.contains(p))throw new IllegalArgumentException("El ID no pertenece a la búsqueda.");}else return;System.out.println(p);System.out.println("1) Nombre  2) Precio  3) Stock  4) Categoría  0) Cancelar");switch(Validaciones.entero(sc,"Opción: ")){case 1:p.setNombre(Validaciones.texto(sc,"Nombre: "));break;case 2:p.setPrecio(Validaciones.decimal(sc,"Precio: ",false));break;case 3:p.setStock(Validaciones.noNegativo(sc,"Stock: "));break;case 4:categorias.listar().forEach(System.out::println);p.setCategoria(categorias.buscar(Validaciones.positivo(sc,"ID categoría: ")));break;default:return;}System.out.println("Actualizado: "+p);}
 private static void menuPedidos(){int op;do{System.out.println("\n--- PEDIDOS ---\n1) Crear pedido\n2) Listar pedidos\n0) Volver");op=Validaciones.entero(sc,"Opción: ");try{switch(op){case 1:crearPedido();break;case 2:pedidos.listarPedidos();break;case 0:break;default:System.out.println("Opción inválida.");}}catch(Exception e){System.out.println("Error: "+e.getMessage());}}while(op!=0);}
 private static void crearPedido()throws Exception{if(productos.getProductos().isEmpty()){System.out.println("No hay productos.");return;}productos.listarProductos();int n=Validaciones.positivo(sc,"Cantidad de líneas: ");List<LineaPedido> lineas=new ArrayList<>();for(int i=0;i<n;i++){Producto p=productos.buscarPorId(Validaciones.positivo(sc,"ID producto: "));int cantidad=Validaciones.positivo(sc,"Cantidad: ");lineas.add(new LineaPedido(p,cantidad));}double total=0;for(LineaPedido l:lineas){System.out.println(l);total+=l.calcularSubtotal();}System.out.printf("TOTAL: $%.2f%n",total);if(!Validaciones.confirmar(sc,"¿Confirmar? (S/N): ")){System.out.println("Cancelado sin descontar stock.");return;}Pedido pedido=pedidos.crearPedido(lineas);System.out.printf("Pedido #%d confirmado. Total: $%.2f%n",pedido.getId(),pedido.calcularTotal());}
 private static void cargarEjemplos(){Categoria general=new Categoria(1,"General","Productos generales"),bebidas=new Categoria(2,"Bebidas","Productos líquidos"),comidas=new Categoria(3,"Comidas","Alimentos");categorias.guardar(general);categorias.guardar(bebidas);categorias.guardar(comidas);productos.agregarProducto(new ProductoGeneral("Café Premium",8500,20,general));productos.agregarProducto(new Bebida("Agua Mineral",1500,30,bebidas,0.5));productos.agregarProducto(new Comida("Galletitas",2300.5,15,comidas,LocalDate.of(2027,12,31)));}
}
