/**
 * Proyecto: TechLab - Sistema de gestión de productos y pedidos
 * Desarrollador: Pablo De Lillo
 *
 * Este es el punto de entrada. Muestro el menú y conecto las opciones con los servicios.
 */
package com.techlab.app;
import com.techlab.productos.*;import com.techlab.pedidos.*;import com.techlab.servicios.*;import com.techlab.excepciones.*;
import java.util.*;import java.time.LocalDate;import java.time.format.DateTimeParseException;
public class Main {
 // Mantengo el menú separado de las reglas de negocio para que sea más fácil de seguir.
 private static final Scanner scanner=new Scanner(System.in);
 private static final ProductoService productos=new ProductoService();private static final PedidoService pedidos=new PedidoService();
 private static final Categoria general=new Categoria(1,"General","Productos generales"), bebidas=new Categoria(2,"Bebidas","Productos líquidos"), comidas=new Categoria(3,"Comidas","Alimentos");
 public static void main(String[] args){cargarEjemplos();int op;do{System.out.println("\n===== SISTEMA DE GESTIÓN - TECHLAB =====\n1) Agregar producto\n2) Listar productos\n3) Buscar/Actualizar producto\n4) Eliminar producto\n5) Crear un pedido\n6) Listar pedidos\n7) Salir");op=leerInt("Elija una opción: ");switch(op){case 1:agregar();break;case 2:productos.listarProductos();break;case 3:buscarActualizar();break;case 4:eliminar();break;case 5:crearPedido();break;case 6:pedidos.listarPedidos();break;case 7:System.out.println("Hasta luego.");break;default:System.out.println("Opción inválida.");}}while(op!=7);}
 private static void agregar(){try{System.out.println("1) General  2) Bebida  3) Comida");int tipo=leerInt("Tipo: ");if(tipo<1||tipo>3){System.out.println("Tipo inválido.");return;}String nombre=leerTexto("Nombre: ");double precio=leerDoubleNoNegativo("Precio: ");int stock=leerIntNoNegativo("Stock: ");Producto p;if(tipo==2)p=new Bebida(nombre,precio,stock,bebidas,leerDoublePositivo("Volumen en litros: "));else if(tipo==3)p=new Comida(nombre,precio,stock,comidas,leerFecha("Vencimiento (AAAA-MM-DD): "));else p=new ProductoGeneral(nombre,precio,stock,general);productos.agregarProducto(p);System.out.println("Agregado: "+p);}catch(IllegalArgumentException e){System.out.println("Error: "+e.getMessage());}}
 private static void buscarActualizar(){try{System.out.println("1) Buscar por ID  2) Buscar por nombre");int tipo=leerInt("Opción: ");Producto p;if(tipo==1)p=productos.buscarPorId(leerInt("ID: "));else if(tipo==2){List<Producto> encontrados=productos.buscarPorNombre(leerTexto("Nombre: "));for(Producto x:encontrados)System.out.println(x);p=productos.buscarPorId(leerInt("ID a seleccionar: "));if(!encontrados.contains(p)){System.out.println("El ID no pertenece a los resultados.");return;}}else{System.out.println("Opción inválida.");return;}System.out.println(p);if(!confirmar("¿Actualizar? (S/N): "))return;System.out.println("1) Precio  2) Stock  3) Nombre  4) Cancelar");int op=leerInt("Opción: ");switch(op){case 1:p.setPrecio(leerDoubleNoNegativo("Nuevo precio: "));break;case 2:p.setStock(leerIntNoNegativo("Nuevo stock: "));break;case 3:p.setNombre(leerTexto("Nuevo nombre: "));break;default:return;}System.out.println("Actualizado: "+p);}catch(ProductoNoEncontradoException|IllegalArgumentException e){System.out.println("Error: "+e.getMessage());}finally{System.out.println("Búsqueda/actualización finalizada.");}}
 private static void eliminar(){try{productos.listarProductos();Producto p=productos.buscarPorId(leerInt("ID a eliminar: "));System.out.println(p);if(confirmar("¿Confirma eliminación? (S/N): ")){productos.eliminarPorId(p.getId());System.out.println("Producto eliminado.");}else System.out.println("Cancelado.");}catch(ProductoNoEncontradoException e){System.out.println(e.getMessage());}}
 private static void crearPedido(){if(productos.getProductos().isEmpty()){System.out.println("No hay productos.");return;}productos.listarProductos();int n=leerIntPositivo("Cantidad de líneas del pedido: ");List<LineaPedido> lineas=new ArrayList<>();for(int i=0;i<n;i++){try{Producto p=productos.buscarPorId(leerInt("ID producto "+(i+1)+": "));int cantidad=leerIntPositivo("Cantidad: ");lineas.add(new LineaPedido(p,cantidad));}catch(ProductoNoEncontradoException e){System.out.println(e.getMessage());i--;}}System.out.println("--- RESUMEN ---");double total=0;for(LineaPedido l:lineas){System.out.println(l);total+=l.calcularSubtotal();}System.out.printf("TOTAL: $%.2f%n",total);if(!confirmar("¿Confirmar pedido? (S/N): ")){System.out.println("Cancelado, sin descontar stock.");return;}try{Pedido pedido=pedidos.crearPedido(lineas);System.out.println("Pedido confirmado #"+pedido.getId()+". Total $"+String.format("%.2f",pedido.calcularTotal()));}catch(StockInsuficienteException|IllegalArgumentException e){System.out.println("Pedido rechazado: "+e.getMessage());}}
 private static boolean confirmar(String mensaje){return leerTexto(mensaje).equalsIgnoreCase("S");}
 private static String leerTexto(String mensaje){while(true){System.out.print(mensaje);String s=scanner.nextLine().trim();if(!s.isEmpty())return s;System.out.println("No puede estar vacío.");}}
 private static int leerInt(String mensaje){while(true){try{return Integer.parseInt(leerTexto(mensaje));}catch(NumberFormatException e){System.out.println("Ingresá un entero válido.");}}}
 private static int leerIntNoNegativo(String m){while(true){int n=leerInt(m);if(n>=0)return n;System.out.println("No puede ser negativo.");}}
 private static int leerIntPositivo(String m){while(true){int n=leerInt(m);if(n>0)return n;System.out.println("Debe ser mayor que cero.");}}
 private static double leerDouble(String m){while(true){try{double n=Double.parseDouble(leerTexto(m).replace(',','.'));if(Double.isFinite(n))return n;System.out.println("Número no finito.");}catch(NumberFormatException e){System.out.println("Ingresá un decimal válido.");}}}
 private static double leerDoubleNoNegativo(String m){while(true){double n=leerDouble(m);if(n>=0)return n;System.out.println("No puede ser negativo.");}}
 private static double leerDoublePositivo(String m){while(true){double n=leerDouble(m);if(n>0)return n;System.out.println("Debe ser positivo.");}}
 private static LocalDate leerFecha(String m){while(true){try{return LocalDate.parse(leerTexto(m));}catch(DateTimeParseException e){System.out.println("Usá AAAA-MM-DD.");}}}
 private static void cargarEjemplos(){productos.agregarProducto(new ProductoGeneral("Café Premium",8500,20,general));productos.agregarProducto(new Bebida("Agua Mineral",1500,30,bebidas,0.5));productos.agregarProducto(new Comida("Galletitas",2300.5,15,comidas,LocalDate.of(2027,12,31)));}
}
